language: node_js
cache: npm
dist: bionic

branches:
  only:
  - master
  - /^release\/.*$/

node_js:
  - 'lts/*'
  - 'node'

stages:
  - check

os:
  - linux
  - osx
  - windows

script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir dep-check
        - npm run lint

notifications:
  email: false
